force-app/main/default/objects/mycustom2__c/mycustom2__c.object-meta.xml
<CustomObject>
    <label>mycustom2</label>
    <nameField>
        <label>mycustom2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>mycustom2s</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/mycustom2__c/fields/Translate__c.field-meta.xml
<CustomField>
    <fullName>Translate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Translate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Office_Location__c/Office_Location__c.object-meta.xml
<CustomObject>
    <label>Office Location</label>
    <nameField>
        <label>Office Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Office Locations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Office_Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Srilanka</fullName>
            </value>
            <value>
                <fullName>WestIndies</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>NewzeLand</fullName>
            </value>
            <value>
                <fullName>Paris</fullName>
            </value>
            <value>
                <fullName>Iceland</fullName>
            </value>
            <value>
                <fullName>Rashya</fullName>
            </value>
            <value>
                <fullName>America</fullName>
            </value>
            <value>
                <fullName>situé dans</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office_Location__c/fields/Country_french__c.field-meta.xml
<CustomField>
    <fullName>Country_french__c</fullName>
    <label>Country_french</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Amérique</fullName>
            </value>
            <value>
                <fullName>Inde</fullName>
            </value>
            <value>
                <fullName>Australie</fullName>
            </value>
            <value>
                <fullName>Srilanka</fullName>
            </value>
            <value>
                <fullName>nouvelle-Zélande</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Office_Location__c/fields/mycustom2__c.field-meta.xml
<CustomField>
    <fullName>mycustom2__c</fullName>
    <label>mycustom2</label>
    <referenceTo>mycustom2__c</referenceTo>
    <relationshipLabel>Office Locations</relationshipLabel>
    <relationshipName>Office_Locations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/sampleCon12.cls
public class sampleCon12{
    public string selectedpickvalue{get;set;}
    public List<SelectOption> options;
   public List<SelectOption> countries{get;set;}
    
    Office_Location__c of1;
    public sampleCon12(ApexPages.StandardController con) {
    Id i=Apexpages.currentpage().getparameters().get('ParentId');
    mycustom2__c m=[select Translate__c from mycustom2__c where id=:i LIMIT 1];
    countries = new List<SelectOption>();
    Schema.DescribeFieldResult fieldResult =Office_Location__c.Country__c.getDescribe();
    Schema.DescribeFieldResult fieldResult1 =Office_Location__c.Country_french__c.getDescribe();
    List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    List<Schema.PicklistEntry> ple1 = fieldResult1.getPicklistValues();
    if(m.Translate__c==false){
        for( Schema.PicklistEntry f : ple)
        {
            countries.add(new SelectOption(f.getLabel(),f.getValue()));
        } 
    }else{
            countries.add(new SelectOption('America','Amérique'));
            countries.add(new SelectOption('India','Inde'));
            countries.add(new SelectOption('Australia','Australie'));
            countries.add(new SelectOption('Srilanka','Srilanka'));
            countries.add(new SelectOption('NewZeland','nouvelle-Zélande'));
    }     
  }
  public void clicking(){
  
  }
}