force-app/main/default/objects/mycustom__c/mycustom__c.object-meta.xml
<CustomObject>
    <label>mycustom</label>
    <nameField>
        <label>mycustom record name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>mycustoms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/mycustom__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/mycustom__c/fields/mycustoname__c.field-meta.xml
<CustomField>
    <fullName>mycustoname__c</fullName>
    <label>mycustoname</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/custom.cls
Public  class custom{
public list<mycustom__c> my{get;set;}
public Boolean exp1{get;set;}
public Boolean exp2{get;set;}
public mycustom__c c{get;set;}

public mycustom__c c1;
public custom(){
exp1=true;
exp2=false;
c=new mycustom__c();
my=[select amount__c,mycustoname__c, id from mycustom__c];


}
 public void update1() {
 exp1=false;
 exp2=true;

       
        
    }
    public void save(){
      c1= new mycustom__c();
     c1.mycustoname__c=c.mycustoname__c;
     c1.amount__c=c.amount__c;
      
   insert c1;
    }

}