force-app/main/default/objects/Bucket__c/Bucket__c.object-meta.xml
<CustomObject>
    <label>Bucket</label>
    <nameField>
        <label>Bucket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buckets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Element__c/Element__c.object-meta.xml
<CustomObject>
    <label>Element</label>
    <nameField>
        <label>Element Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Element__c/fields/Bucket__c.field-meta.xml
<CustomField>
    <fullName>Bucket__c</fullName>
    <label>Bucket</label>
    <referenceTo>Bucket__c</referenceTo>
    <relationshipLabel>Elements</relationshipLabel>
    <relationshipName>Elements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Element__c/fields/Parent_Element__c.field-meta.xml
<CustomField>
    <fullName>Parent_Element__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Element</label>
    <referenceTo>Element__c</referenceTo>
    <relationshipLabel>Elements</relationshipLabel>
    <relationshipName>Elements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/hierarchyClass.cls
public class hierarchyClass{
    public hierarchyClass(){
    }
    map<id,List<element__c>> elementMap = new map<id,List<element__c>>();
        
    public void hierarchyMethod(){
    
        Map<id,Bucket__c> bucketMap = new map<id,bucket__c>([Select id from Bucket__c]);
        List<element__c> elementList = [Select id, Bucket__c,parent_element__c FROM Element__c where bucket__c IN:bucketMap.keySet()];
        for(element__c ele :elementList) {
            if(ele.Parent_element__c == null) {
                elementMap.put(ele.bucket__c,new List<element__c>{ele});
            } else {
                if(elementMap.containsKey(ele.Parent_element__c) && elementMap.get(ele.Parent_element__c) != null) {
                    elementMap.get(ele.Parent_element__c).add(ele);
                    
                } else {
                    elementMap.put(ele.parent_element__c,new List<element__c>{ele});
                }
            }
            
        }
        
        
        for(bucket__c buc : bucketMap.values()){
            jsonstr = jsonstr +'{ name:'+buc.name;
            if(elementMap.get(buc.id) != null) {
                jsonstr = jsonstr +'items:[';
                prepareJson(elementMap.get(buc.id));
            }
            
        }
        jsonstr = jsonstr +']';  
    }
    String jsonstr = '[';
    private void prepareJson(List<Element__c> elements){
        for(element__c ele : elements){
            jsonstr = jsonstr +'{ name:'+ele.name;
             if(elementMap.get(ele.id) != null) {
                jsonstr = jsonstr +'items:[';
                prepareJson(elementMap.get(ele.id));
            } else{
                jsonstr = jsonstr+'}'; 
            }
        }
        
        jsonstr = jsonstr +']';    
    
    }

}